/**
 * SVG 处理器纯函数测试
 */

import { describe, it, expect } from 'vitest';
import {
  ensureNamespaces,
  wrapStyleWithCdata,
  extractSvgDimensions,
  calculatePaddedViewBox,
  generateHtmlWrapper,
  generateMarkdownContent,
} from '../svgProcessor';

describe('svgProcessor', () => {
  describe('ensureNamespaces', () => {
    it('should add xmlns when missing', () => {
      const svg = '<svg><rect width="100" height="100"/></svg>';
      const result = ensureNamespaces(svg);
      expect(result).toContain('xmlns="http://www.w3.org/2000/svg"');
    });

    it('should preserve existing xmlns', () => {
      const svg = '<svg xmlns="http://www.w3.org/2000/svg"><rect/></svg>';
      const result = ensureNamespaces(svg);
      expect(result.match(/xmlns=/g)?.length).toBe(1);
    });

    it('should add xmlns:xlink when xlink is used', () => {
      // 注意：DOMParser 可能会改变 xlink 前缀的处理方式
      // 所以我们测试一个已经包含 xlink namespace 的 SVG
      const svg =
        '<svg xmlns:xlink="http://www.w3.org/1999/xlink"><a xlink:href="http://example.com"><text>Link</text></a></svg>';
      const result = ensureNamespaces(svg);
      expect(result).toContain('xmlns:xlink="http://www.w3.org/1999/xlink"');
    });

    it('should return original content when no svg element', () => {
      const notSvg = '<div>not an svg</div>';
      const result = ensureNamespaces(notSvg);
      expect(result).toBe(notSvg);
    });
  });

  describe('wrapStyleWithCdata', () => {
    it('should wrap style content with CDATA', () => {
      const style = '.test { fill: red; }';
      const result = wrapStyleWithCdata(style);
      expect(result).toContain('/*<![CDATA[*/');
      expect(result).toContain('/*]]>*/');
      expect(result).toContain(style);
    });

    it('should not wrap if already contains CDATA', () => {
      const style = '/*<![CDATA[*/ .test { fill: red; } /*]]>*/';
      const result = wrapStyleWithCdata(style);
      expect(result).toBe(style);
    });

    it('should return empty string as is', () => {
      expect(wrapStyleWithCdata('')).toBe('');
    });
  });

  describe('extractSvgDimensions', () => {
    it('should extract width and height attributes', () => {
      const svg = '<svg width="200" height="150"><rect/></svg>';
      const result = extractSvgDimensions(svg);
      expect(result).toEqual({ width: 200, height: 150 });
    });

    it('should extract from viewBox when width/height missing', () => {
      const svg = '<svg viewBox="0 0 300 200"><rect/></svg>';
      const result = extractSvgDimensions(svg);
      expect(result).toEqual({ width: 300, height: 200 });
    });

    it('should return default dimensions for invalid SVG', () => {
      const svg = '<div>not an svg</div>';
      const result = extractSvgDimensions(svg);
      expect(result).toEqual({ width: 800, height: 600 });
    });

    it('should handle zero dimensions', () => {
      const svg = '<svg width="0" height="0" viewBox="0 0 100 50"><rect/></svg>';
      const result = extractSvgDimensions(svg);
      expect(result).toEqual({ width: 100, height: 50 });
    });
  });

  describe('calculatePaddedViewBox', () => {
    it('should calculate padded viewBox', () => {
      const result = calculatePaddedViewBox('0 0 100 50', 10);
      expect(result).toBe('-10 -10 120 70');
    });

    it('should handle non-zero origin', () => {
      const result = calculatePaddedViewBox('10 20 100 50', 5);
      expect(result).toBe('5 15 110 60');
    });

    it('should return null for invalid viewBox', () => {
      expect(calculatePaddedViewBox('invalid', 10)).toBeNull();
      expect(calculatePaddedViewBox('0 0 100', 10)).toBeNull(); // only 3 values
    });
  });

  describe('generateHtmlWrapper', () => {
    it('should generate valid HTML document', () => {
      const svg = '<svg><rect/></svg>';
      const result = generateHtmlWrapper(svg, 'Test Diagram');

      expect(result).toContain('<!DOCTYPE html>');
      expect(result).toContain('<html lang="zh-CN">');
      expect(result).toContain('<title>Test Diagram</title>');
      expect(result).toContain(svg);
      expect(result).toContain('Generated by GraphViewer');
    });

    it('should escape HTML in title', () => {
      const result = generateHtmlWrapper('<svg/>', '<script>alert("xss")</script>');
      expect(result).not.toContain('<script>alert');
      expect(result).toContain('&lt;script&gt;');
    });
  });

  describe('generateMarkdownContent', () => {
    it('should generate markdown with code fence', () => {
      const code = 'graph TD\n  A --> B';
      const result = generateMarkdownContent(code, 'mermaid', 'test-diagram');

      expect(result).toContain('# test-diagram');
      expect(result).toContain('```mermaid');
      expect(result).toContain(code);
      expect(result).toContain('Generated by GraphViewer');
    });

    it('should handle different languages', () => {
      const code = 'digraph { A -> B }';
      const result = generateMarkdownContent(code, 'dot', 'graphviz-test');

      expect(result).toContain('```dot');
      expect(result).toContain('# graphviz-test');
    });
  });
});
