/**
 * SVG 预处理纯函数
 *
 * 所有函数都是纯函数或确定性函数，可独立测试
 *
 * @deprecated 推荐使用 SvgPreprocessor 类，这些函数保留用于向后兼容
 */

import type { ExportOptions, ProcessedSvg } from './types';
import { svgPreprocessor } from './SvgPreprocessor';

/**
 * HTML 转义
 */
function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;');
}

/**
 * 确保 SVG 命名空间正确
 *
 * @deprecated 内部实现细节，不应直接调用
 * @param svgContent SVG 内容
 * @returns 添加了正确命名空间的 SVG 内容
 */
export function ensureNamespaces(svgContent: string): string {
  const parser = new DOMParser();
  const doc = parser.parseFromString(svgContent, 'image/svg+xml');
  const svgElement = doc.querySelector('svg');

  if (!svgElement) {
    return svgContent;
  }

  if (!svgElement.hasAttribute('xmlns')) {
    svgElement.setAttribute('xmlns', 'http://www.w3.org/2000/svg');
  }
  if (!svgElement.hasAttribute('xmlns:xlink') && svgContent.includes('xlink:')) {
    svgElement.setAttribute('xmlns:xlink', 'http://www.w3.org/1999/xlink');
  }

  return new XMLSerializer().serializeToString(svgElement);
}

/**
 * 包装 style 标签内容为 CDATA
 *
 * @deprecated 内部实现细节，不应直接调用
 * @param styleContent style 标签内容
 * @returns 包装后的内容
 */
export function wrapStyleWithCdata(styleContent: string): string {
  if (!styleContent || styleContent.includes('CDATA')) {
    return styleContent;
  }
  return `\n/*<![CDATA[*/\n${styleContent}\n/*]]>*/\n`;
}

/**
 * 计算添加 padding 后的 viewBox
 *
 * @deprecated 内部实现细节，不应直接调用
 * @param viewBox 原始 viewBox 字符串
 * @param padding 内边距
 * @returns 新的 viewBox 字符串，如果计算失败返回 null
 */
export function calculatePaddedViewBox(viewBox: string, padding: number): string | null {
  const parts = viewBox.split(/\s+/).map(Number);
  if (parts.length !== 4) return null;

  const [minX = 0, minY = 0, width = 0, height = 0] = parts;
  return `${minX - padding} ${minY - padding} ${width + padding * 2} ${height + padding * 2}`;
}

/**
 * 内联 SVG 元素的重要样式属性
 *
 * @deprecated 内部实现细节，不应直接调用
 * 注意：此函数需要访问 window.getComputedStyle，因此有 DOM 依赖
 * 但仍然是确定性的：相同输入产生相同输出
 *
 * @param svgContent SVG 内容
 * @param properties 要内联的属性列表
 * @returns 处理后的 SVG 内容
 */
export function inlineComputedStyles(
  svgContent: string,
  properties: string[] = [
    'fill',
    'stroke',
    'stroke-width',
    'font-family',
    'font-size',
    'font-weight',
    'opacity',
  ],
): string {
  if (typeof window === 'undefined') {
    return svgContent;
  }

  const parser = new DOMParser();
  const doc = parser.parseFromString(svgContent, 'image/svg+xml');
  const svgElement = doc.querySelector('svg');

  if (!svgElement) {
    return svgContent;
  }

  const allElements = svgElement.querySelectorAll('*');
  allElements.forEach((element) => {
    if (element instanceof SVGElement) {
      const computedStyle = window.getComputedStyle(element);
      properties.forEach((prop) => {
        const value = computedStyle.getPropertyValue(prop);
        if (value && value !== 'none' && !element.hasAttribute(prop)) {
          element.setAttribute(prop, value);
        }
      });
    }
  });

  return new XMLSerializer().serializeToString(svgElement);
}

/**
 * 预处理 SVG（组合函数）
 *
 * @deprecated 请使用 svgPreprocessor.preprocess()
 * @param svgContent 原始 SVG 内容
 * @param options 导出选项
 * @returns 处理结果
 */
export function preprocessSvg(
  svgContent: string,
  options: Partial<ExportOptions> = {},
): ProcessedSvg {
  return svgPreprocessor.preprocess(svgContent, options);
}

/**
 * 提取 SVG 尺寸信息
 *
 * @deprecated 请使用 svgPreprocessor.extractDimensions()
 * @param svgContent SVG 内容
 * @returns 宽度和高度
 */
export function extractSvgDimensions(svgContent: string): { width: number; height: number } {
  return svgPreprocessor.extractDimensions(svgContent);
}

/**
 * 生成 HTML 包装
 *
 * @param svgContent SVG 内容
 * @param title 标题
 * @returns 完整的 HTML 文档
 */
export function generateHtmlWrapper(svgContent: string, title: string): string {
  return `<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(title)}</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body {
      min-height: 100vh;
      display: flex;
      align-items: center;
      justify-content: center;
      background: linear-gradient(135deg, #f5f7fa 0%, #c3cfe2 100%);
      padding: 2rem;
    }
    .container {
      background: white;
      border-radius: 16px;
      box-shadow: 0 20px 60px rgba(0,0,0,0.1);
      padding: 2rem;
      max-width: 100%;
      overflow: auto;
    }
    svg {
      display: block;
      max-width: 100%;
      height: auto;
    }
    .footer {
      margin-top: 1rem;
      text-align: center;
      font-size: 12px;
      color: #999;
    }
  </style>
</head>
<body>
  <div class="container">
    ${svgContent}
    <div class="footer">Generated by GraphViewer</div>
  </div>
</body>
</html>`;
}

/**
 * 生成 Markdown 内容
 *
 * @param code 源代码
 * @param lang 语言标识
 * @param filename 文件名
 * @returns Markdown 内容
 */
export function generateMarkdownContent(code: string, lang: string, filename: string): string {
  return `# ${filename}

\`\`\`${lang}
${code}
\`\`\`

---
*Generated by GraphViewer*
`;
}
